name: Update GIF in Markdown

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Allows modifying the repository

jobs:
  update-gif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # check day of week
      - name: Check Day of Week
        id: day-of-week
        run: |
          # Map the numeric day of the week to the day name
          DAY_OF_WEEK_NAME=$(case $(date +"%u") in
            1) echo "Monday" ;;
            2) echo "Tuesday" ;;
            3) echo "Wednesday" ;;
            4) echo "Thursday" ;;
            5) echo "Friday" ;;
            6) echo "Saturday" ;;
            7) echo "Sunday" ;;
            *) echo "Unknown" ;;
          esac)
          echo "DAY_OF_WEEK_NAME=$DAY_OF_WEEK_NAME" >> $GITHUB_ENV
            
      # select random gif by day of week
      - name: Select Random GIF by Day of Week
        id: random-gif-by-day-of-week
        run: |
          ls gifs/day_of_week/${DAY_OF_WEEK_NAME}/*.gif
          SELECTED_Day_of_Week_GIF=$(shuf -n1 -e gifs/day_of_week/${DAY_OF_WEEK_NAME}/*.gif)
          echo "SELECTED_Day_of_Week_GIF=$SELECTED_Day_of_Week_GIF" >> $GITHUB_ENV
      # change week of day 
      - name: Update README with Selected  Day of Week
        run: | 
          sed -i "s|## Today is .*|## Today is ${DAY_OF_WEEK_NAME}|" README.md
          
      # select random gif
      - name: Select Random GIF
        id: random-gif
        run: |
          SELECTED_GIF=$(shuf -n1 -e gifs/start_wars/*.gif)
          echo "SELECTED_GIF=$SELECTED_GIF">> $GITHUB_ENV
      # update week of day
 
      - name: Update README with Selected GIF by Day of Week
      # update README with selected gif
        run: |
          sed -i "s|https://github.com/FANJIYU0825/FANJIYU0825/blob/main/gifs/day_of_week/Friday/Friday_ITS_FRIDAY.gif|https://github.com/FANJIYU0825/FANJIYU0825/blob/main/'$SELECTED_Day_of_Week_GIF'|" README.md

      - name: Update README with Selected GIF
        run: |
          sed -i "s|https://github.com/FANJIYU0825/FANJIYU0825/blob/main/gifs/start_wars/.*.gif|https://github.com/FANJIYU0825/FANJIYU0825/blob/main/'$SELECTED_GIF'|" README.md
      
      # update README with counting day
      - name: counting the day I start coding 
        run: |
            X=$(( ($(date +%s) - $(date -d "2019-10-01" +%s)) / 86400 ))
            echo "Day start coding= $X"
            sed -i "s|start coding for [0-9]* day|start coding for $X day|" README.md
            
     
      - name: Force Git to Detect Changes
        run: |
          git status
          git diff
          git add README.md
          git status
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git commit -m "Auto-update GIF $(date)" || echo "No changes to commit"
          git add README.md
          git push 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
