name: Update GIF in Markdown

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Allows modifying the repository

jobs:
  update-gif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # check day of week
      - name: Check Day of Week
        id: day-of-week
        run: |
          case $DAY_OF_WEEK in
          1) WEEKDAY="Monday" ;;
          2) WEEKDAY="Tuesday" ;;
          3) WEEKDAY="Wednesday" ;;
          4) WEEKDAY="Thursday" ;;
          5) WEEKDAY="Friday" ;;
          6) WEEKDAY="Saturday" ;;
          7) WEEKDAY="Sunday" ;;
         
          esac
          echo "DAY_OF_WEEK=$WEEKDAY" >> $GITHUB_ENV
            
      # select random gif by day of week
      - name: Select Random GIF by Day of Week
        id: random-gif-by-day-of-week
        run: |
          ls gifs/${DAY_OF_WEEK}/*.gif
          SELECTED_Day_of_Week_GIF=$(shuf -n1 -e gifs/${env.DAY_OF_WEEK}/*.gif)
          echo "SELECTED_Day_of_Week_GIF=$SELECTED_Day_of_Week_GIF" >> $GITHUB_ENV
      # change week of day 
      - name: Update README with Selected GIF by Day of Week
        run: | 
        
          sed -i "s|Today is \[\]|Today is ${DAY_OF_WEEK}|" README.md
          sed -i "s|https://github.com/FANJIYU0825/FANJIYU0825/blob/main/gifs/day_of_week/Friday/Friday_ITS_FRIDAY.gif|https://github.com/FANJIYU0825/FANJIYU0825/blob/main/$SELECTED_Day_of_Week_GIF|" README.md

      # select random gif
      - name: Select Random GIF
        id: random-gif
        run: |
          SELECTED_GIF=$(shuf -n1 -e gifs/start_wars/*.gif)
          echo "SELECTED_GIF=$SELECTED_GIF">> $GITHUB_ENV
      # update README with selected gif
      - name: Update README with Selected GIF
        run: |
          sed -i "s|https://github.com/FANJIYU0825/FANJIYU0825/blob/main/gifs/start_wars/.*.gif|https://github.com/FANJIYU0825/FANJIYU0825/blob/main/$SELECTED_GIF|" README.md
      
      # update README with counting day
      - name: counting the day I start coding 
        run: |
            X=$(( ($(date +%s) - $(date -d "2019-10-01" +%s)) / 86400 ))
            echo "Day start coding= $X"
            sed -i "s|start coding for [0-9]* day|start coding for $X day|" README.md
            
     
      - name: Force Git to Detect Changes
        run: |
          git status
          git diff
          git add README.md
          git status
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git commit -m "Auto-update GIF $(date)" || echo "No changes to commit"
          git add README.md
          git push 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
